### ISSUE TITLE
While buffering, the status you return to /torrents?status=true is 3 and it should be 9

### ISSUE THREAD

**Issue by lopezvg** [i96751414/torrest-cpp#1]
While buffering, the status you return to /torrents?status=true is 3 and it should be 9:

```
info [api] [thread-15660] operation=intercept, method=GET, address=127.0.0.1, uri=/torrents?status=true, elapsedTime=0, statusCode=200
{'info_hash': 'adad99d3e5e5587c548495b761c9829bf6ddeb4a', 'name': 'Los Dos Papas (2019) [BluRay RIP][AC3 5.1 Castellano][[www.pctnew.ORG](http://www.pctnew.org/)][[www.descargas2020.ORG](http://www.descargas2020.org/)]', 'size': 2094031085, 'status': {'total': 2094031085, 'total_done': 9961472, 'total_wanted': 2094031085, 'total_wanted_done': 9961472, 'progress': 0.4757000207901001, 'download_rate': 810343, 'upload_rate': 23876, 'paused': False, 'has_metadata': True, 'state': 3, 'seeders': 5, 'seeders_total': 19, 'peers': 0, 'peers_total': 2, 'seeding_time': 0, 'finished_time': 0, 'active_time': 21, 'all_time_download': 8585216, 'all_time_upload': 0}}
```

**Comment by i96751414** [comment]
Thank you for the info. I will have a look.

**Comment by i96751414** [comment]
This can now be done. You will have to pass `-Denable_torrent_buffering_status=ON` to cmake so this feature is enabled.

**Comment by lopezvg** [comment]
Thank you, I'll test ir as soon as I can.

By the way, I've been testing Kodi 20 to check compatibility issues.  I've made Torrest to work fine, but with several changes that I would like to share with you:

REPO: (full updated repo .zip enclosed)
- addon.xml: now "dir" labels are not optional anymore and are required in extension structure.  With this error the repo will not install
- kodi.py, entries.py: xbmc.translatePath has been replaced by xbmcvfs.translatePath

TORREST addon: (only changed files are enclosed)
- kodi.py, dialog.py, service.py: xbmc.translatePath has been replaced by txbmcvfs.ranslatePath
- dialog.py: from xbmcgui import ACTION_PARENT_DIR, ACTION_NAV_BACK, ACTION_PREVIOUS_MENU, does not work.  I haven't been able to find if this is an incompatibility issue or just a release bug.  I have provided a quick and dirty solution in lines 7-14.  Please investigate.

[repository.github-0.0.7.zip](https://github.com/i96751414/torrest-cpp/files/8747269/repository.github-0.0.7.zip)
[Torrest.zip](https://github.com/i96751414/torrest-cpp/files/8747272/Torrest.zip)

**Comment by i96751414** [comment]
Thank you. I will certainly do the fixes
