### ISSUE TITLE
documentation 

### ISSUE THREAD

**Issue by omgbox** [i96751414/torrest-cpp#2]
found it under http://localhost:8080/swagger/ui

how would i invoke streaming automatically through the rest api, http://localhost:8080/stream?magnet=magnetLink or Hash

how to open this automatically through the command line or terminal directly to mpv or vlc

**Comment by i96751414** [comment]
Hi. You have all the API reference under swagger and also in docs: https://github.com/i96751414/torrest-cpp/blob/master/docs/rest-api.md

The endpoint you are trying to call (`http://localhost:8080/stream?magnet=magnetLink`) does not exist.
You have to:
1. Add the magnet (POST /add/magnet)
2. Start the download of the file you want (PUT /torrents/{infoHash}/files/{file}/download)
3. Serve the file in vlc or any other player (GET /torrents/{infoHash}/files/{file}/serve)

**Comment by omgbox** [comment]
> Hi. You have all the API reference under swagger and also in docs: https://github.com/i96751414/torrest-cpp/blob/master/docs/rest-api.md
> 
> The endpoint you are trying to call (`http://localhost:8080/stream?magnet=magnetLink`) does not exist. You have to:
> 
> 1. Add the magnet (POST /add/magnet)
> 2. Start the download of the file you want (PUT /torrents/{infoHash}/files/{file}/download)
> 3. Serve the file in vlc or any other player (GET /torrents/{infoHash}/files/{file}/serve)

thank you
