### ISSUE TITLE
Cleaning installation using install_dependencies.sh on Ubuntu OS

### ISSUE THREAD

**Issue by puppinoo** [i96751414/torrest-cpp#4]
Hi,
I generated the binary using the script above.
It worked but then I decided to switch to docker image.
Unfortunately the available space on my VPS is very limited and install_dependencies.sh used about 1.5GB downloading and installing various dependencies.
Is there a way to revert the installation made by CMake so I can free used space and switch to a docker image?
Real newbie here so sorry if stupid question. Before asking I searched online but didnt find anything useful.

Thanks.

**Comment by i96751414** [comment]
Hi,

I am not sure I understood your question. You created a docker image for building the binary?

**Comment by puppinoo** [comment]
> Hi,
> 
> I am not sure I understood your question. You created a docker image for building the binary?

Hi and thanks for reply.
No, I first used the install_dependencies.sh script to create the binary then I decided to switch to a docker image instead but I still have all the dependencies from the script installed and since the vps has very limited space Id like to remove them from system. I dunno how to do that so I was wondering if cmakle installation from the script provides a "uninstall" option.

Cheers.

**Comment by i96751414** [comment]
Ah, you mean uninstalling from the system, not docker image. Got it.

I think CMake does not provide with that option, however you can manually delete the files listed in install_manifest.txt for each of the dependency. Unfortunately the script automatically deletes all the build files after completing, so you would have to play around with the script a bit.

Nevertheless, you should confirm the 1.5GB were a consequence of this script. It seems more than I would expect for compiled libs (as the script cleans downloaded stuff upon completion). Note that docker images can be very large in size as well.

**Comment by puppinoo** [comment]
Hi and thanks for reply,
I read online that removing files into install_manifest.txt is the proper way to unistall.
Unfortunately your script doesn't seem to create any install_manifest.txt file.
Can you confirm that?
Maybe it's just me too dumb to find it.
If file not created is the case is there another way to unistall?

Also the 1.5Gb of used space was a loose assumption based on what I recalled as previous free space but could be wrong. Sorry for that.

Thanks.

**Comment by i96751414** [comment]
No need to be sorry ;)

I'll try to update the script to somehow support removing dependencies or to provide with an install_manifest.txt.
