### ISSUE TITLE
Environment and Volumes variables for a hand made docker-compose?

### ISSUE THREAD

**Issue by puppinoo** [i96751414/torrest-cpp#5]
Hi,
Real Newbie here.
I'm trying to manually create a docker-compose yml file pointing to i96751414/torrest-cpp-linux-x64:latest

A blank one works but can I pass volumes and environment variables?

Thanks.

This one (correctly indented, I dont know how to do that. Sorry) passes the docker-compose config command:

`
services:
  torrest:
    image: i96751414/torrest-cpp-linux-x64:latest
    container_name: torrest
    restart: unless-stopped
`

**Comment by i96751414** [comment]
Hi.

Please bear in mind that these images are for cross compiling, they don't have the torrest binary. If that's what you want, you will have to create tour image with the torrest binary. Then you will be able to mount any volumes you need as well as passing any environment variantes.

**Comment by puppinoo** [comment]
Yes,
I didn't understand the purpose of them.
I created my own docker image with a proper binary.
Thanks a lot for clarification.

Pino.
