### ISSUE TITLE
Download streamed file or every file in .torrent

### ISSUE THREAD

**Issue by ladoba** [i96751414/torrest-cpp#6]
Hi @i96751414 .

Is there any chance for this feature?If you stream a file you could select what you want, download only the streamed file or every file what .torrent file includes.

**Comment by i96751414** [comment]
Hi. I think this is already implemented. Can you please further explain to make sure I understood what you want?

**Comment by ladoba** [comment]
Hi.
Torrest download only what you streaming.(mkv,avi etv) ,BUT .torrent file may contain other files like nfo,cover.jpg etc.If you do not download every single file you will remain leecher and not seeder.I have a lot of private tracker accounts where it is not too good to use it like this.at the moment I use torrest to stream torrents and when I start a stream ,.torrent file appears in downloads/torrent folder which is also the qbittorrent's watch folder.Qbittorrent download those missing files and seed them later.I hope I was able to describe it clearly.

Thanks,
L

**Comment by i96751414** [comment]
Indeed torrest already does that. Before streaming you can start the download for all torrent files and only after you would stream.

**Comment by ladoba** [comment]
I tried something.You are right.if I use torrest locally or remotely and add .torrent file manually, it works perfectly. But if I use it inside Kodi with an addon (jacktook), torrest only download the streamed file. In this case something wrong with jacktook addon.
